### ISSUE TITLE
Install script didn't work for Octoprint install

### ISSUE THREAD

**Issue by wolfman1138** [geeekpi/RPB-HAT#5]
Hi,
I want to add the Makerfocus IR Switch to my Octoprint installation on the RPi3.  When I followed the instructions and ran the install script, it looked like it properly installed. but I didn't see a shutdown command being run.  

Looking deeper , It looks like the "/etc/rc.local" did not contain any of the shutdown code.  I attempted to paste in code from "/etc/init.d/remoteswitch" but I am not sure if it is working now.  
I see the STA flash for a while, then it goes down.  But I don't see any Shutdown messages in my open terminals.  Is that normal?

thanks!
-Wolfman

**Comment by yoyojacky** [comment]
sorry for the late response,  i think you may not install the scripts correctly... seems like the code may not sync.   if you press shutdown or reboot button or just press the button on IR remote controller, it will show a screen that you can see it shutdown properly... if not, you may need to reinstall the driver.
